import {
	type KataganaWord,
	kataganaWord,
	type Word,
	word,
} from "@components/WordsDisplay/WordsDisplay";

export default {
	words: [
		word("心当たり", "こころあたり", "n.想象"),
		word("引っ越し会社", "ひっこしかいしゃ", "n.搬家公司"),
		word("原稿", "げんこう", "n.原稿"),
		word("裾", "すそ", "n.下摆"),
		word("外す", "はずす", "v.拆卸,脱下"),
		word("秘書課", "ひしょか", "n.秘书处"),
		word("候補日", "こうほび", "n.备选日期"),
		word("絞る", "しぼる", "v.缩小"),
		word("塗る", "ぬる", "v.涂抹"),
		word("動かす", "うごかす", "v.移动"),
		word("文字", "もじ", "n.文字"),
		word("放課後", "ほうかご", "n.放学之后"),
		word("対応", "たいおう", "n/v.对应,应对方式,对策,对待的行为"),
		word("昼間", "ひるま", "n.白天"),
		word("洗練する", "せんれんする", "v.磨练,精炼"),
		word("一流", "いちりゅう", "n.一流"),
		word("慣れる", "なれる", "v.习惯"),
		word("親しむ", "したしむ", "v.亲近"),
		word("気候", "きこう", "n.气候,氛围"),
		word("冊", "さつ", "n.册"),
		word("じっくり", "じっくり", "adv.认真地"),
		word("成るべく", "なるべく", "v.尽可能的"),
		word("辿る", "たどる", "v.沿路前进"),
		word("愚痴", "ぐち", "n/v.抱怨"),
		word("検討", "けんとう", "n/v.考虑,讨论"),
		word("直径", "ちょっけい", "n.直径"),
		word("柔軟", "じゅうなん", "adj.柔软的"),
	] as Word[],
	kataganaWords: [
		kataganaWord("スニーカー", "sneaker", "n.球鞋"),
		kataganaWord("サークル", "circle", "n.社团"),
	] as KataganaWord[],
};
